### ISSUE TITLE
Why the parameter --num_classes is 200 in io_utils.py?

### ISSUE THREAD

**Issue by ztf-ucas** [liubingyuu/FTEM_BSR_CDFSL#1]
This is a excellent work! I have a question when reproduing this code.
The model is pre-trained on the meta-training set of miniImageNet with 64 classes or on the entire miniImageNet with 100 classes?
Thank you very much!

**Comment by liubingyuu** [comment]
Thanks! We pre-train the model on the meta-training set of miniImageNet with 64 classes following the CD-FSL challenge.
