### ISSUE TITLE
请问模型是在什么任务上验证以选择模型参数的？

### ISSUE THREAD

**Issue by WHQ1111** [liubingyuu/FTEM_BSR_CDFSL#2]
我有个疑问，在跨域的少样本学习问题中是否还可以在miniImageNet的验证集上验证模型？这个时候miniImageNet的验证集上的性能似乎已经无法体现目标域上的性能。

**Comment by liubingyuu** [comment]
miniImageNet的验证集上确实无法体现目标域的性能，在miniImageNet上的结果我们只用作参考选择pre-trained模型，最终我们是通过目标域的验证集来选择参数的。
